[tool.poetry]
name = "patterns"
version = "0.1.0"
description = ""
authors = ["serega <scherbinin@lanit.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
